# Generated by Django 4.2.2 on 2023-07-02 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.ManyToManyField(related_name='registered_events', through='events.Registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
